### ISSUE TITLE
Error: image dockerfile/nodejs:latest not found

### ISSUE THREAD

**Issue by juanpabloaj** [tutumcloud/quickstart-node#1]
In the dockerfile you use `dockerfile/nodejs:latest`

https://github.com/tutumcloud/quickstart-node/blob/master/Dockerfile#L1

this container exists ? 

when I use this line in a docker file I get this error message

```
Error: image dockerfile/nodejs:latest not found
```

**Comment by fermayo** [comment]
Fixed in f4cd8b44dd94ae8129ce42f8176983087ff3cbbe !
